version: '3'
services: 
  web:
    container_name: redes
    ports:
      - "8080:80"
    image: nginx
    networks:
      - net-test
  web2:
    container_name: redes2
    ports:
      - "8081:80"
    image: httpd
    networks:
      - net-test
networks:
  net-test: